baseURL = "https://openvalue-b.github.io/blog/"
themesDir = "themes"
publishDir = "docs"
languageCode = "en-US"
title = "OpenValue | Blog"
theme = "openvalue-blog-theme"
author = "authors"
tag = "tags"
category = "categories"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true